# Form implementation generated from reading ui file 'c:\Users\justi\Desktop\期末專題\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(652, 401)
        self.playimage = QtWidgets.QGraphicsView(parent=Form)
        self.playimage.setGeometry(QtCore.QRect(20, 50, 441, 241))
        self.playimage.setObjectName("playimage")
        self.sits = QtWidgets.QComboBox(parent=Form)
        self.sits.setGeometry(QtCore.QRect(20, 20, 361, 22))
        self.sits.setObjectName("sits")
        self.sits.addItem("")
        self.sits.addItem("")
        self.sits.addItem("")
        self.start = QtWidgets.QPushButton(parent=Form)
        self.start.setGeometry(QtCore.QRect(470, 300, 161, 81))
        self.start.setObjectName("start")
        self.output = QtWidgets.QTextBrowser(parent=Form)
        self.output.setGeometry(QtCore.QRect(470, 20, 161, 211))
        self.output.setObjectName("output")
        self.working = QtWidgets.QTextBrowser(parent=Form)
        self.working.setGeometry(QtCore.QRect(20, 300, 441, 81))
        self.working.setObjectName("working")
        self.yessit = QtWidgets.QPushButton(parent=Form)
        self.yessit.setGeometry(QtCore.QRect(390, 20, 71, 21))
        self.yessit.setObjectName("yessit")
        self.drawline = QtWidgets.QPushButton(parent=Form)
        self.drawline.setGeometry(QtCore.QRect(470, 240, 61, 51))
        self.drawline.setObjectName("drawline")
        self.replay = QtWidgets.QPushButton(parent=Form)
        self.replay.setGeometry(QtCore.QRect(380, 260, 81, 31))
        self.replay.setObjectName("replay")
        self.yesline = QtWidgets.QPushButton(parent=Form)
        self.yesline.setGeometry(QtCore.QRect(540, 240, 91, 51))
        self.yesline.setObjectName("yesline")
        self.annoimage = QtWidgets.QRadioButton(parent=Form)
        self.annoimage.setGeometry(QtCore.QRect(400, 240, 61, 20))
        self.annoimage.setObjectName("annoimage")
        self.rawimage = QtWidgets.QRadioButton(parent=Form)
        self.rawimage.setGeometry(QtCore.QRect(400, 220, 61, 20))
        self.rawimage.setObjectName("rawimage")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sits.setItemText(0, _translate("Form", "國道10號 0K+746 鼎金系統交流道到左營端"))
        self.sits.setItemText(1, _translate("Form", "國道6號 4K+205 舊正交流道到東草屯交流道"))
        self.sits.setItemText(2, _translate("Form", "國道1號 22K+900 內湖交流道到圓山交流道"))
        self.start.setText(_translate("Form", "開始偵測"))
        self.output.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft JhengHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.working.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft JhengHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.yessit.setText(_translate("Form", "確認地點"))
        self.drawline.setText(_translate("Form", "畫線"))
        self.replay.setText(_translate("Form", "重新播放影片"))
        self.yesline.setText(_translate("Form", "完成畫線"))
        self.annoimage.setText(_translate("Form", "偵測"))
        self.rawimage.setText(_translate("Form", "原始"))
